#!/bin/bash

#PBS -P au38
#PBS -q gpuvolta
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -l walltime=12:00:00
#PBS -l mem=64GB
#PBS -l storage=gdata/au38

source /g/data/au38/yy3740/miniconda3/bin/activate clam_latest

# Extract features for new tif imgs
python3 /g/data/au38/CLAM/extract_features_fp.py \
--data_h5_dir /g/data/au38/yy3740/hpa_train_full_feats \
--data_slide_dir /g/data/au38/yy3740/hpa_train_full_stack \
--csv_path /g/data/au38/CLAM/dataset_csv/train_hpa.csv \
--feat_dir /g/data/au38/yy3740/hpa_train_full_feats \
--batch_size 512 --slide_ext .tif

